name: Deploy tooot API services
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { package: ['push', 'translate'] }

    steps:
      - name: -- Step 0 -- Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: -- Step 1 -- Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: -- Step 2 -- Publish
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: './packages/${{ matrix.package }}'
        run: yarn && yarn build --define:process.env.RELEASE=\"${{ github.sha }}\" && yarn deploy
      - name: -- Step 4 -- Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ matrix.package }}
        with:
          sourcemaps: './packages/${{ matrix.package }}/dist'
          url_prefix: '/dist/'
